name: build + run.sh

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build -t altserver:latest .

      # Push the image to docker hub
      - name: Push image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag altserver:latest ${{ secrets.DOCKER_USERNAME }}/altserver:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/altserver:latest


